<?php
$parameters = array(
	'db_driver' => 'pdo_mysql',
	'db_host' => 'localhost',
	'db_table_prefix' => 'mt',
	'db_port' => '3306',
	'db_name' => 'mautic',
	'db_user' => 'root',
	'db_password' => 'root',
	'db_backup_tables' => 1,
	'db_backup_prefix' => 'mtbkp_',
	'db_server_version' => '5.7.20-0ubuntu0.16.04.1',
	'mailer_from_name' => 'Marcuss Johnn',
	'mailer_from_email' => 'marcussjohnn@gmail.com',
	'mailer_transport' => 'mail',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => null,
	'mailer_password' => null,
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%kernel.root_dir%/spool',
	'secret_key' => '832bd07c8541c8ecc6021c1b22787d219ecb4fc14634585753d29fa5a400827b',
	'site_url' => 'http://localhost/MyProjects/Symfony/mautic/index.php',
);
